// Generated by Lona Compiler 0.9.1

import React from "react"
import { Text, View, StyleSheet } from "react-native"

import colors from "colors"
import shadows from "shadows"
import textStyles from "textStyles"

export default class LonaTest extends React.Component {
  render() {


    let canvas.height
    let canvas.index

    if (canvas.height === canvas.index) {


    }

    return (
      <View style={styles.view}>
        <Text style={styles.text}>
          {"Text goes here"}
        </Text>
        <View style={styles.view1} />
      </View>
    );
  }
};

let styles = StyleSheet.create({
  view: {
    alignItems: "flex-start",
    alignSelf: "stretch",
    flex: 0,
    flexDirection: "column",
    justifyContent: "flex-start"
  },
  text: {
    ...textStyles.defaultStyle,
    alignItems: "flex-start",
    flex: 0,
    flexDirection: "column",
    justifyContent: "flex-start"
  },
  view1: {
    alignItems: "center",
    alignSelf: "stretch",
    backgroundColor: "#D8D8D8",
    flexDirection: "row",
    justifyContent: "center",
    marginRight: 10,
    marginLeft: 10,
    height: 100
  }
})